spring: # test profile
  datasource:
    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
jwt:
  secret: "b9ba604a99274bf89bfafdaf95ae5a9bdasdsafassaf"
  access-token-expire-time: 1800000
  refresh-token-expire-time: 2592000000