name: Backend Build & Deploy

on:
  push:
    branches:
      - main # main 브랜치에 push가 발생하면 workflow가 실행됩니다.
permissions:
  contents: read # 레포지토리의 컨텐츠를 읽을 수 있습니다.

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository # 현재 레포지토리를 체크아웃합니다.
        uses: actions/checkout@v4

      - name: Set up JDK 17 # JDK 17을 설치합니다.
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Give execute permission # 권한을 부여합니다.
        run: chmod +x gradlew

      - name: Build with Gradle # Gradle로 빌드합니다.
        run: ./gradlew clean build

      - name: Build docker image and push to docker hub # Docker 이미지를 빌드하고 Docker Hub에 푸시합니다.
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}